<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="windows-clone" name="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource" tests="11" failures="0" timestamp="23 Jul 2018 07:30:51 GMT" time="0.000" errors="11">
  <testcase name="del_table" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_table.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_table.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_table.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.del_tabledata(HbaseResource.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- del_table -->
  <testcase name="create_data" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_data.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_data.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_data.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.create_datadata(HbaseResource.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- create_data -->
  <testcase name="update_table" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_table.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_table.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_table.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.update_tabledata(HbaseResource.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- update_table -->
  <testcase name="del_data" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_data.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_data.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_data.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.del_datadata(HbaseResource.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- del_data -->
  <testcase name="update_data" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_data.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_data.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_data.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.update_datadata(HbaseResource.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- update_data -->
  <testcase name="check_table" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_table.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_table.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_table.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.check_tabledata(HbaseResource.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- check_table -->
  <testcase name="del_space" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_space.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_space.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\del_space.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.del_spacedata(HbaseResource.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- del_space -->
  <testcase name="create_table" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_table.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_table.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_table.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.create_tabledata(HbaseResource.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- create_table -->
  <testcase name="check_space" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_space.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_space.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\check_space.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.check_spacedata(HbaseResource.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- check_space -->
  <testcase name="create_space" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_space.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_space.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\create_space.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.create_spacedata(HbaseResource.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- create_space -->
  <testcase name="update_space" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_space.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_space.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\Hbase资源配额管理\data\update_space.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource.update_spacedata(HbaseResource.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- update_space -->
</testsuite> <!-- com.DWP.多租户管理.资源配额管理.Hbase资源配额管理.script.HbaseResource -->
