<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="windows-clone" name="com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource" tests="4" failures="0" timestamp="23 Jul 2018 07:30:51 GMT" time="0.000" errors="4">
  <testcase name="check" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\check.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\check.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\check.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource.checkdata(KafkaResource.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- check -->
  <testcase name="create" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\create.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\create.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\create.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource.createdata(KafkaResource.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- create -->
  <testcase name="delete" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\delete.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\delete.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\delete.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource.deletedata(KafkaResource.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- delete -->
  <testcase name="modify" time="0.000" classname="com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\modify.xls (设备未就绪。)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\modify.xls (设备未就绪。)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.DWP.runalltest.AllTestRun.main(AllTestRun.java:40)
Caused by: java.io.FileNotFoundException: D:\software\intellij idea\IdeaProjects\DWP_Season3\src\com\DWP\多租户管理\资源配额管理\kafka配额管理\data\modify.xls (设备未就绪。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.publicfunction.publicFunction.ReadData(publicFunction.java:396)
	at com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource.modifydata(KafkaResource.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 18 more
]]>
    </error>
  </testcase> <!-- modify -->
</testsuite> <!-- com.DWP.多租户管理.资源配额管理.Kafka配额管理.script.KafkaResource -->
